In [17]:
import numpy as np
import copy

X = np.array([ [1,2,3],
               [2,3,4],
               [3,4,5],
               [4,5,6]])
w = np.array([10,20,30])

In [18]:

X.shape

(4, 3)

In [20]:
# = X
Y = copy.deepcopy(X)

for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w
print(X)
print(Y)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[21 42 63]
 [22 43 64]
 [23 44 65]
 [24 45 66]]


In [22]:
Y = X + w
print(Y)

[[21 42 63]
 [22 43 64]
 [23 44 65]
 [24 45 66]]


In [26]:
w = np.array([1,2,3,4], ndmin=2).T
Z = Y*w
print(Z)

[[ 21  42  63]
 [ 44  86 128]
 [ 69 132 195]
 [ 96 180 264]]


In [29]:
v = np.arange(0,9)
print(v)
M = np.reshape(v, (3,3))
print(M)
C = np.tile(M, (3,1))
print(C)
B = C*np.reshape(v, (len(v), 1))
print(B)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]
